import React, { useState } from "react";
import "../components/css/SearchBar.css";

// here i define the props for the searchBar which is only a string and i return a void which is nothing
interface SearchBarProps {
  onSearch: (query: string) => void;
}
// here we define our searchBar component which takes onSearch as an argument
const SearchBar: React.FC<SearchBarProps> = ({ onSearch }) => {
  //this hook is responsible for storing the current search query and intializing it with an empty string

  const [query, setQuery] = useState("");

  // i originally made this even handler using useEffect but i decided to remove it for simplicity
  //React.ChangeEvent<HTMLInputElement> is event generated by a change in an HTML input element
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    // this creates a variable called newQuery which contains the value of the input
    const newQuery = e.target.value;
    // This  updates the state variable query with the new value from the input field.
    setQuery(newQuery);
    // here we call the the onsearch function while passing our new value
    // in my first prototype i was calling the function with a search button but this is honestly much more convenient
    onSearch(newQuery);
  };
  return (
    <div className="search-bar">
      <input
        type="text"
        value={query}
        onChange={handleInputChange}
        placeholder="Search for movies"
        className="search-bar__input"
      />
    </div>
  );
};

export default SearchBar;
